# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Lvblanc/android_kernel_xiaomi_sm8635
          kernel-branch: lineage-23.0
          config: defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          other-clang-url: true
          other-clang-branch: master
          ksu: false
          android-version: 12
          aosp-clang-version: r596125
          disable-lto: true
          anykernel3: true
